site_name: MAQUETTE
nav:
    - Accueil: accueil.md
    - Code: code.md
    - Tutoriel: tutoriel.md
    - Autre: autre.md
    - Contactez-nous: contactez-nous.md
    - English: https://siu-kevin.github.io/mock-up/home/
theme:
    name: mkdocs
    custom_dir: custom_theme/
    locale: fr
    color_mode: dark
    nav_style: dark
    user_color_mode_toggle: false
extra_css: [style.css]
